#!/bin/bash

if g++ a1q3.cc;
then
	number=""
	if [ "$#" -eq 1 ]; then
		number="$1"
	else
		echo How many nodes?
		read number
	fi
	FILES=randTSP/$number/*
	for f in $FILES
	do
		echo "Processing $f file..."
#		cat $f
		time ./a.out < $f
	done
	rm a.out
else
	echo "Failed compile"
fi
